# Generated by Django 5.2.1 on 2025-05-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lliga',
            name='data_inici',
            field=models.DateField(null=True),
        ),
    ]
