# Generated by Django 5.2.1 on 2025-05-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0003_alter_lliga_data_fi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip',
            name='fundacio',
            field=models.IntegerField(null=True),
        ),
    ]
