# Generated by Django 5.2.1 on 2025-05-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0004_alter_equip_fundacio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partit',
            name='gols_local',
        ),
        migrations.RemoveField(
            model_name='partit',
            name='gols_visitant',
        ),
    ]
